# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup env
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      
      - name: Download test file
      - uses: carlosperate/download-file-action@v1
      - with:
           file-url: 'https://github.com/tangowithcode/tango_with_django_2_code/raw/master/progress_tests/tests_chapter3.py'
      - name: Run tests
      - run:  python manage.py test rango.tests_chapter3
